services:
    cloudstack:
        image: apache/cloudstack-simulator:4.20.0.0
        container_name: cloudstack-mcp-simulator
        platform: linux/amd64
        ports:
            - "8080:8080"
            - "8443:8443"
            - "8250:8250"
            - "4560:4560"
        networks:
            - cloudstack-network
        volumes:
            - cloudstack-data:/var/lib/cloudstack
        restart: unless-stopped
        environment:
            - TZ=UTC
        tmpfs:
            - /tmp
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8080/client"]
            interval: 45s
            timeout: 15s
            retries: 5
            start_period: 240s

    cloudmonkey:
        build:
            context: .
            dockerfile: docker/cloudmonkey.Dockerfile
        container_name: cloudstack-mcp-cmk
        platform: linux/amd64
        networks:
            - cloudstack-network
        volumes:
            - cloudmonkey-data:/root/.cmk
        depends_on:
            cloudstack:
                condition: service_healthy
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "cmk", "list", "zones"]
            interval: 45s
            timeout: 15s
            retries: 5
            start_period: 240s

        entrypoint: ["/bin/sh", "-c", "/usr/local/bin/docker-entrypoint.sh"]

    mcp-server-sse:
        build:
            context: .
            dockerfile: docker/server.Dockerfile
        container_name: cloudstack-mcp-sse
        ports:
            - "8251:8250"
        environment:
            - CLOUDSTACK_API_URL=http://cloudstack:8080/client/api
            - MCP_ADDR=:8250
            - CLOUDSTACK_USERNAME=admin
            - CLOUDSTACK_PASSWORD=password
            - LOG_LEVEL=debug
        networks:
            - cloudstack-network
        depends_on:
            cloudstack:
                condition: service_healthy
        restart: unless-stopped

    mcp-server-stdio:
        profiles:
            - stdio
        build:
            context: .
            dockerfile: docker/server.Dockerfile
        container_name: cloudstack-mcp-stdio
        environment:
            - CLOUDSTACK_API_URL=http://cloudstack:8080/client/api
            - CLOUDSTACK_USERNAME=admin
            - CLOUDSTACK_PASSWORD=password
            - LOG_LEVEL=debug
        networks:
            - cloudstack-network
        command: ["/app/server", "-http=false"]

networks:
    cloudstack-network:
        driver: bridge

volumes:
    cloudstack-data:
        driver: local
        driver_opts:
            type: "none"
            o: "bind"
            device: ${PWD}/.tmp/cloudstack-data
    cloudmonkey-data:
        driver: local
