version: "3"

vars:
    GO_MODULES:
        sh: cat go.work | grep -oEh  '\t+(\./*[^[:space:]]*)' | tr -d '\t'
    JSONSCHEMA_FILES:
        sh: find . -type f -name '*.schema.json'
    GO_ROOT_PKG:
        sh: cat go.mod | grep -oE '^module[^\S]+' | cut -d' ' -f2

env:
    COMPOSE_BAKE: true

tasks:
    go-mod-tidy:
        env: { GOPROXY: https://proxy.golang.org, GOSUMDB: sum.golang.org, GOPRIVATE: github.com/walteh }
        cmds:
            - for: { var: GO_MODULES }
              cmd: cd {{.ITEM}} && go mod tidy

    go-mod-upgrade:
        run: once
        env: { GOPROXY: https://proxy.golang.org, GOSUMDB: sum.golang.org, GOPRIVATE: github.com/walteh }
        cmds:
            - ./go tool go-mod-upgrade --force

    options:
        desc: generates options for structs with '//go:opts' comment
        vars:
            OPTION_GEN_DATA:
                sh: |
                    grep -rl "//go:opts" --include="*.go" . | xargs -I{} bash -c 'd=$(dirname {}); d=${d#./}; awk -v d="$d {}" '\''/\/\/go:opts/ {getline; if($1=="type") print d, $2}'\'' {}'
            OPTION_GEN_SOURCE_FILES:
                sh: |
                    grep -rl "//go:opts" --include="*.go" .
        generates:
            - "**/*_opts.gen.go"
        sources:
            - '{{.OPTION_GEN_SOURCE_FILES | join ","}}'
        cmds:
            - for: { var: OPTION_GEN_DATA, split: "\n" }
              cmd: |
                  ./go tool github.com/kazhuravlev/options-gen/cmd/options-gen \
                    -out-filename={{splitList " " .ITEM | first}}/{{ splitList " " .ITEM | last | lower | trimSuffix "opts" }}_opts.gen.go \
                    -filename={{ splitList " " .ITEM | rest | first }} \
                    -from-struct={{ splitList " " .ITEM | last }} \
                    -pkg={{ splitList " " .ITEM | first | splitList "/" | last }}

    mockery:
        desc: generates mocks for interfaces with '//go:mock' comment
        vars:
            TMP_DIR: ./gen/config
            MOCKERY_INTERFACE_DATA:
                sh: |
                    grep -rl "//go:mock" --include="*.go" . | xargs -I{} bash -c 'd=$(dirname {}); d=${d#./}; awk -v d="$d {}" '\''/\/\/go:mock/ {getline; if($1=="type") print d, $2}'\'' {}'
            MOCKERY_SOURCE_FILES:
                sh: |
                    grep -rl "//go:mock" --include="*.go" .
        sources:
            - '{{.MOCKERY_SOURCE_FILES | join ","}}'
            - .mockery.yaml
        generates:
            - ./gen/mocks/**/*_mock.gen.go
            - ./gen/config/.mockery.yaml
        cmds:
            - cmd: mkdir -p {{.TMP_DIR}}
            - cmd: cp .mockery.yaml {{.TMP_DIR}}/.mockery.yaml
            - for: { var: "MOCKERY_INTERFACE_DATA", split: "\n", as: ITEM }
              cmd: yq -i ".packages.\"{{ .GO_ROOT_PKG }}/{{ splitList " " .ITEM | first }}\".interfaces.{{ splitList " " .ITEM | last }} = {}" {{.TMP_DIR}}/.mockery.yaml
            - cmd: ./go tool github.com/vektra/mockery/v2 --config={{.TMP_DIR}}/.mockery.yaml

    cmk:
        desc: Run CloudMonkey command in Docker container
        cmds:
            - bash ./scripts/cmk.sh {{.CLI_ARGS}}

    mcp:service-account:check:
        desc: Check MCP service account status
        cmds:
            - | #bash
                bash ./scripts/cmk.sh list users username=mcp-service

    docker:start:
        desc: Start CloudStack and MCP server using Docker Compose
        cmds:
            - docker compose --progress=tty up -d --wait --build

    docker:restart:
        desc: Start CloudStack and MCP server using Docker Compose
        cmds:
            - task: docker:stop
            - task: docker:start

    docker:stop:
        desc: Stop CloudStack and MCP server
        cmds:
            - docker compose --progress=tty down

    docker:build:
        desc: Build Docker images for MCP and CloudMonkey
        cmds:
            - docker compose --progress=tty build

    run:server:
        desc: Run the MCP server
        cmds:
            - ./go run ./cmd/server

    build:
        desc: Build the MCP server
        cmds:
            - ./go build -o bin/server ./cmd/server

    vm:launch:
        desc: Launch a VM
        cmds:
            - mkdir -p ./.tmp/cloudstack-agent-mnt
            - cp ./vm-configs/cloudstack-agent.cloud-init.yaml ./.tmp/cloudstack-agent-mnt/cloud-init.yaml
            - yq -i ".users[0].ssh_authorized_keys[0] = \"$(cat ~/.ssh/walteh.git.pub)\"" ./.tmp/cloudstack-agent-mnt/cloud-init.yaml
            - alpine launch -n cloudstack-agent --arch aarch64 --cpu 4 --memory 4096 --disk 20G --ssh 2922 --mount ./.tmp/cloudstack-agent-mnt --image nocloud_alpine-3.21.2-aarch64-uefi-cloudinit-r0.qcow2
            - alpine exec cloudstack-agent -- ash -c "/mnt/cloudstack-agent-mnt/alpine-setup-cloud-init.sh"

            - alpine exec cloudstack-agent -- ash -c "cloud-init -f /mnt/cloud-init.yaml init && cloud-init -f /mnt/cloud-init.yaml modules"

    jsonschema:lima:
        desc: Generate JSON schema for Lima
        cmds:
            - ./go tool github.com/lima-vm/lima/cmd/limactl generate-jsonschema > gen/config/lima.schema.json

    # vm:incus:
    #     desc: Launch a VM using Incus
    #     cmds:
    #         - ./go tool macpine launch --name incus --ssh 223 --port 8449:8443
    #         - ./go tool macpine exec incus -- "hwclock -s; wget https://raw.githubusercontent.com/beringresearch/macpine/main/scripts/enable_incus.sh"
    #         - ./go tool macpine exec incus -- "ash enable_incus.sh"
    #         - echo "sleeping for 10 seconds" && sleep 10
    #         # - ./go tool macpine exec incus -- "lxc ipv4.address=10.10.10.1/24"
    #         - ./go tool macpine exec incus "incus config set core.https_address 0.0.0.0:8443"
    #         - ./go tool macpine exec incus "incus admin init --auto --network-address=0.0.0.0"
    #         - ./go tool macpine exec incus "incus config trust add mymac"
    #         - incus remote add incus https://127.0.0.1:8449
    #         - incus remote switch incus
