version: "3"

tasks:
    default:
        cmds:
            - task -l
        silent: true

    cloudstack:setup:create-vm:
        desc: Create the CloudStack VM
        cmds:
            - echo "Setting up CloudStack environment..."
            - bash ./scripts/setup-cloudstack.sh

    cmk:
        desc: Run CloudMonkey command in Docker container
        cmds:
            - bash ./scripts/cmk.sh {{.CLI_ARGS}}

    docker:start:
        desc: Start CloudStack and MCP server using Docker Compose
        cmds:
            - docker-compose up -d --wait

    docker:restart:
        desc: Start CloudStack and MCP server using Docker Compose
        cmds:
            - task: docker:stop
            - task: docker:start

    docker:stop:
        desc: Stop CloudStack and MCP server
        cmds:
            - docker-compose down

    docker:build:
        desc: Build Docker images for MCP and CloudMonkey
        cmds:
            - docker-compose build

    run:server:
        desc: Run the MCP server
        cmds:
            - go run ./cmd/server

    build:
        desc: Build the MCP server
        cmds:
            - go build -o bin/server ./cmd/server

    clean:
        desc: Clean build artifacts
        cmds:
            - rm -rf bin
            - rm -rf .tmp
